# **Matrix Manipulation**

---

**Exercise 1.** Write a Python function that takes two integer numbers `m` and `n` as input and creates the `m x n` Hilbert matrix. The Hilbert matrix has elements of the form `a[i,j]=1/(i+j-1)`. 

**Exercise 2.** Build a RHS vector `b` for solving a linear system with the square Hilbert matrix (`H`) of order 5 such that the solution is the vector of all 1. Solve the system and get the solution `x`. Now perturb `b` with the vector `db=[0,0,0,0,1e-4]` and compute the new solution `x1`. Estimate the 2-norm condition number of `H` by means of 

\begin{equation}
\frac{\|x-x_1\|}{\|x\|}\leq \kappa_2 \frac{\|\delta b\|}{\|b\|}
\end{equation}

**Exercise 3.** Compute the condition number of the square Hilbert matrix for `n=5, 10, 100`.

## **Solution**

### **Exercise 1**

In [120]:
def HilbertMatrix(m, n):
  "This build an Hilbert Matrix of m-rows and n-column"
  import numpy as np

  H = np.zeros((m, n))

  for i in range(m):
    for j in range(n):
      H[i, j] = 1/(i+1+j+1-1)

  return H

help(HilbertMatrix)

Help on function HilbertMatrix in module __main__:

HilbertMatrix(m, n)
    This build an Hilbert Matrix of m-rows and n-column



### **Exercixe** **2**



In [121]:
#b construction
x = np.ones((5, 1))
H=HilbertMatrix(5, 5)
b=np.dot(H, x)

#Verification
Hinv=np.linalg.inv(H)
print('Verification')
print(np.dot(Hinv, b).T)
print()

#Perturbation
db=np.array([[0,0,0,0,1e-4]])
bpert=b+db.T

xpert=np.dot(Hinv, bpert)
K2=(np.linalg.norm(xpert-x)/np.linalg.norm(x))/(np.linalg.norm(db)/np.linalg.norm(b))
print('K2 estimated is ' + str(K2))
print('K2 calculated with numpy is ' + str(np.linalg.cond(H)))

Verification
[[1. 1. 1. 1. 1.]]

K2 estimated is 160624.13166621252
K2 calculated with numpy is 476607.25024259434


### **Esercizio 3**



In [122]:
for i in [5, 10, 100]:
  H=HilbertMatrix(i, i)
  print('The condition number of the Hilbert Matrix of dimention ' + str(i) + 'x' + str(i) + ' is ' + str(np.linalg.cond(H)))

The condition number of the Hilbert Matrix of dimention 5x5 is 476607.25024259434
The condition number of the Hilbert Matrix of dimention 10x10 is 16024416992541.715
The condition number of the Hilbert Matrix of dimention 100x100 is 2.525412746419138e+19


# **Eigenvalue**

---



**Exercise 1.** Take a look at the document available at __[www.cs.huji.ac.il/~csip/tirgul2.pdf](http://www.cs.huji.ac.il/~csip/tirgul2.pdf)__ describing the power method for calculating the largest eigenvalue of a matrix. Write a Python function that takes as input the matrix `A`, the initial guess of the eigenvector `x0` and the maximum number of iteration `itmax` and returns the maximum eigenvalue and the corresponding eigenvector.

**Exercise 2.** Implement the inverse power method. This method is the original method applied to the matrix $A^{-1}$. With reference to the solution of Exercise 1 it must be noticed that in this case the computation of `q` (lines 3 and 9) requires the solution of a linear system (to this aim use `np.linalg.solve`). 

**Exercise 3.** Implement the inverse power method with shift. This method is the original method applied to the matrix $(A-\lambda I)^{-1}$; the user has to supply $\lambda$ (the _shift_ ) and the algorithm will find the closest eigenvalue to $\lambda$.

## **Solution**

### **Exercise 1**

In [123]:
import numpy as np

def PowerMethod(A, x0, tol, itMax):
  k=1
  err=tol+1
  q=x0
  while np.linalg.norm(err)>tol and itMax>=k:
      k=k+1
      qold=q
      z=np.dot(A, q)
      q=z/np.linalg.norm(z)
      lam=np.dot(q.T, np.dot(A, q))
      err=q-qold
      k=k+1
  return q, lam

A=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
[q, lam]=PowerMethod(A, np.ones((3, 1)), 1e-4, 500)

print('The eingenvector is')
print(q)
print()
print('The eigenvalue is')
print(lam)

print()
print()
print('Using numpy:')
np.linalg.eig(A)

The eingenvector is
[[0.16475942]
 [0.50577311]
 [0.8467868 ]]

The eigenvalue is
[[13.34844525]]


Using numpy:


(array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

### **Exercise 2**

In [124]:
import numpy as np

def invPowerMethod(A, x0, tol, itMax):
  k=1
  err=tol+1
  q=x0
  while np.linalg.norm(err)>tol and itMax>=k:
      k=k+1
      qold=q
      z=np.linalg.solve(A, q)
      q=z/np.linalg.norm(z)
      lam=np.dot(q.T, np.dot(A, q))
      err=q-qold
      k=k+1
  return q, lam

A=np.array([[1, 1, 2], [3, 4, 5], [6, 7, 8]])
[q, lam]=invPowerMethod(A, np.ones((3, 1)), 1e-4, 500)

print('The eingenvector is')
print(q)
print()
print('The eigenvalue is')
print(lam)

print()
print()
print('Using numpy:')
np.linalg.eig(A)

The eingenvector is
[[ 0.68307992]
 [-0.72002042]
 [ 0.12236183]]

The eigenvalue is
[[0.30419626]]


Using numpy:


(array([13.43012421,  0.30419711, -0.73432132]),
 array([[-0.17657562, -0.68307299, -0.60665189],
        [-0.50434253,  0.7200255 , -0.36269072],
        [-0.84525716, -0.12237067,  0.70741001]]))

### **Exercise 3**

In [125]:
import numpy as np

def invSwiftPowerMethod(A, x0, tol, itMax, s):
  k=1
  err=tol+1
  q=x0
  while np.linalg.norm(err)>tol and itMax>=k:
      k=k+1
      qold=q
      z=np.linalg.solve((A-s*np.eye(len(A), len(A))), q)
      q=z/np.linalg.norm(z)
      lam=np.dot(q.T, np.dot(A, q))
      err=q-qold
      k=k+1
  return q, lam

A=np.array([[1, 1, 2], [3, 4, 5], [6, 7, 8]])
[q, lam]=invSwiftPowerMethod(A, np.ones((3, 1)), 1e-4, 500, 10)

print('The eingenvector is')
print(q)
print()
print('The eigenvalue is')
print(lam)

print()
print()
print('Using numpy:')
np.linalg.eig(A)

The eingenvector is
[[0.17655584]
 [0.50434341]
 [0.84526076]]

The eigenvalue is
[[13.4300324]]


Using numpy:


(array([13.43012421,  0.30419711, -0.73432132]),
 array([[-0.17657562, -0.68307299, -0.60665189],
        [-0.50434253,  0.7200255 , -0.36269072],
        [-0.84525716, -0.12237067,  0.70741001]]))